use_frameworks!

platform :ios, '9.0'

target 'WTLNetWorking_Example' do
  pod 'WTLNetWorking', :path => '../'

  target 'WTLNetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
